package Pensiones;

import Conexion.ConexionSQL;
import Logicas.Logica_permisos;
import Logicas.Logica_usuarios;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JDeat
 */
public final class PensionesVP_7 extends javax.swing.JFrame {

    /**
     * Creates new form PensionesVP_7
     */
    ConexionSQL cc = new ConexionSQL();
    Connection con = cc.conexion();
    Logica_usuarios usr;
    Logica_permisos LP;

    public PensionesVP_7() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(6);
        setIconImage(new ImageIcon(PensionesVP_7.class.getClassLoader().getResource("Imagenes/Icono.png")).getImage());
        MDPEN();
    }

    public PensionesVP_7(Logica_usuarios usr, Logica_permisos LP) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(6);
        setIconImage(new ImageIcon(PensionesVP_7.class.getClassLoader().getResource("Imagenes/Icono.png")).getImage());

        this.usr = usr;
        this.LP = LP;
        MDPEN();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void operaciones() {
        double recargo = 0, IVA = 0;
        if (Rec.isSelected() == true) {
            recargo = 280;
            RecImporte.setText("" + recargo);
        } else {
            recargo = 0;
            RecImporte.setText("" + recargo);

        }
        if (this.IVA.isSelected() == true) {
            IVA = 0.16;
            IVAImporte.setText("" + (Double.parseDouble(Importe.getText()) * IVA));
        } else {
            IVA = 0;
            IVAImporte.setText("" + (Double.parseDouble(Importe.getText()) * IVA));

        }
        double total = (Double.parseDouble(Importe.getText()) * IVA) + Double.parseDouble(Importe.getText()) + recargo;
        TAP.setText("" + total);
    }

    public void MDPEN() {
        String FiltroN = nameiturbide.getText();
        String FAP = Apiturbide.getText();
        String FAM = Amiturbide.getText();
        String where = "SELECT * FROM `pensiones.iturbide`";

        if (!"".equals(FiltroN)) {
            where = "SELECT * FROM `pensiones.iturbide`"
                    + " where `Nombre(s)` LIKE '%" + FiltroN + "%'";
        } else if (!"".equals(FAP)) {
            where = "SELECT * FROM `pensiones.iturbide`"
                    + " Where `Apellido P` LIKE '%" + FAP + "%'";
        } else if (!"".equals(FAM)) {
            where = "SELECT * FROM `pensiones.iturbide`"
                    + " Where `Apellido M` LIKE '%" + FAM + "%'";
        } else if (!"".equals(NPiturbide.getText())) {
            where = "SELECT * FROM `pensiones.iturbide`"
                    + " Where `#padron` LIKE '%" + NPiturbide.getText() + "%'";
        }
        try {
            //Cargar datos
            DefaultTableModel modelo = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int filas, int columna) {
                    return false;
                }

            };
//Nombre de la tabla
            Titurbide.setModel(modelo);
            PreparedStatement ps;
            ResultSet rs;

            ps = con.prepareStatement(where);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("# Registro");
            modelo.addColumn("Apellido P");//4
            modelo.addColumn("Apellido M");
            modelo.addColumn("Nombre(s)");//6
            modelo.addColumn("Direccion");
            modelo.addColumn("Mail");//8
            modelo.addColumn("# CASA");
            modelo.addColumn("# OFICINA");//10
            modelo.addColumn("# Celular");
            modelo.addColumn("Observaciones");//12
            modelo.addColumn("Placas");
            modelo.addColumn("Marca");
            modelo.addColumn("Modelo");
            modelo.addColumn("Año");
            modelo.addColumn("Color");
            modelo.addColumn("Clase de auto");
            modelo.addColumn("Tipo de pension");
            modelo.addColumn("Status");
            modelo.addColumn("Referencia bancaria");
            modelo.addColumn("Razon social");
            modelo.addColumn("# Padron");
            modelo.addColumn("Inicio de pension");
            modelo.addColumn("Fin de pension");
            modelo.addColumn("Importe");
            modelo.addColumn("Recargo");
            modelo.addColumn("IVA");
            modelo.addColumn("Total a pagar");
            modelo.addColumn("Total pagado");
            modelo.addColumn("Fecha de pago");
            modelo.addColumn("Metodo");
            modelo.addColumn("CTE");

//ANCHOS
            int[] anchos = {/*NF*/50, /*NL*/ 50, /*NF*/ 50,/*NE*/ 50, /*AP*/ 60, /*AM*/ 60, /*NAME*/ 50, /*ZON*/ 50,
                /*SERV*/ 50, /*QUIN*/ 60, /*NQ*/ 50, /*PAG*/ 60, /*PEN*/ 60,/*PDODT*/ 60, 70, 70, 70, 70,
                70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70};

            for (int x = 0; x < cantidadColumnas; x++) {
                //Nombre tabla
                Titurbide.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);

            }

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }
        } catch (SQLException error_mpdodt) {
            JOptionPane.showMessageDialog(null, "Error al motrar datos iturbide: " + error_mpdodt.getMessage());

        }
        FiltroN = nameTehuantepec.getText();
        FAP = ApTehuantepec.getText();
        FAM = AmTehuantepec.getText();
        where = "SELECT * FROM `pensiones.tehuantepec`";

        if (!"".equals(FiltroN)) {
            where = "SELECT * FROM `pensiones.tehuantepec`"
                    + " where `Nombre(s)` LIKE '%" + FiltroN + "%'";
        } else if (!"".equals(FAP)) {
            where = "SELECT * FROM `pensiones.tehuantepec`"
                    + " Where `Apellido P` LIKE '%" + FAP + "%'";
        } else if (!"".equals(FAM)) {
            where = "SELECT * FROM `pensiones.tehuantepec`"
                    + " Where `Apellido M` LIKE '%" + FAM + "%'";
        } else if (!"".equals(NPTehuantpec.getText())) {
            where = "SELECT * FROM `pensiones.tehuantepec`"
                    + " Where `#padron` LIKE '%" + NPTehuantpec.getText() + "%'";
        }
        try {
            //Cargar datos
            DefaultTableModel modelo = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int filas, int columna) {
                    return false;
                }

            };
//Nombre de la tabla
            TTehuantepec.setModel(modelo);
            PreparedStatement ps;
            ResultSet rs;

            ps = con.prepareStatement(where);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("# Registro");
            modelo.addColumn("Apellido P");//4
            modelo.addColumn("Apellido M");
            modelo.addColumn("Nombre(s)");//6
            modelo.addColumn("Direccion");
            modelo.addColumn("Mail");//8
            modelo.addColumn("# CASA");
            modelo.addColumn("# OFICINA");//10
            modelo.addColumn("# Celular");
            modelo.addColumn("Observaciones");//12
            modelo.addColumn("Placas");
            modelo.addColumn("Marca");
            modelo.addColumn("Modelo");
            modelo.addColumn("Año");
            modelo.addColumn("Color");
            modelo.addColumn("Clase de auto");
            modelo.addColumn("Tipo de pension");
            modelo.addColumn("Status");
            modelo.addColumn("Referencia bancaria");
            modelo.addColumn("Razon social");
            modelo.addColumn("# Padron");
            modelo.addColumn("Inicio de pension");
            modelo.addColumn("Fin de pension");
            modelo.addColumn("Importe");
            modelo.addColumn("Recargo");
            modelo.addColumn("IVA");
            modelo.addColumn("Total a pagar");
            modelo.addColumn("Total pagado");
            modelo.addColumn("Fecha de pago");
            modelo.addColumn("Metodo");
            modelo.addColumn("CTE");

//ANCHOS
            int[] anchos = {/*NF*/50, /*NL*/ 50, /*NF*/ 50,/*NE*/ 50, /*AP*/ 60, /*AM*/ 60, /*NAME*/ 50, /*ZON*/ 50,
                /*SERV*/ 50, /*QUIN*/ 60, /*NQ*/ 50, /*PAG*/ 60, /*PEN*/ 60,/*PDODT*/ 60, 70, 70, 70, 70,
                70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70};

            for (int x = 0; x < cantidadColumnas; x++) {
                //Nombre tabla
                TTehuantepec.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);

            }

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }
        } catch (SQLException error_mpdodt) {
            JOptionPane.showMessageDialog(null, "Error al motrar dato: " + error_mpdodt.getMessage());

        }
        FiltroN = nameptetitla.getText();
        FAP = Apptetitla.getText();
        FAM = Amptetitla.getText();
        where = "SELECT * FROM `pensiones.puente titla`";

        if (!"".equals(FiltroN)) {
            where = "SELECT * FROM `pensiones.ptetitla`"
                    + " where `Nombre(s)` LIKE '%" + FiltroN + "%'";
        } else if (!"".equals(FAP)) {
            where = "SELECT * FROM `pensiones.puente titla`"
                    + " Where `Apellido P` LIKE '%" + FAP + "%'";
        } else if (!"".equals(FAM)) {
            where = "SELECT * FROM `pensiones.puente titla`"
                    + " Where `Apellido M` LIKE '%" + FAM + "%'";
        } else if (!"".equals(NPptetitla.getText())) {
            where = "SELECT * FROM `pensiones.puente titla`"
                    + " Where `#padron` LIKE '%" + NPptetitla.getText() + "%'";
        }
        try {
            //Cargar datos
            DefaultTableModel modelo = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int filas, int columna) {
                    return false;
                }

            };
//Nombre de la tabla
            Tptetitla.setModel(modelo);
            PreparedStatement ps;
            ResultSet rs;

            ps = con.prepareStatement(where);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("# Registro");
            modelo.addColumn("Apellido P");//4
            modelo.addColumn("Apellido M");
            modelo.addColumn("Nombre(s)");//6
            modelo.addColumn("Direccion");
            modelo.addColumn("Mail");//8
            modelo.addColumn("# CASA");
            modelo.addColumn("# OFICINA");//10
            modelo.addColumn("# Celular");
            modelo.addColumn("Observaciones");//12
            modelo.addColumn("Placas");
            modelo.addColumn("Marca");
            modelo.addColumn("Modelo");
            modelo.addColumn("Año");
            modelo.addColumn("Color");
            modelo.addColumn("Clase de auto");
            modelo.addColumn("Tipo de pension");
            modelo.addColumn("Status");
            modelo.addColumn("Referencia bancaria");
            modelo.addColumn("Razon social");
            modelo.addColumn("# Padron");
            modelo.addColumn("Inicio de pension");
            modelo.addColumn("Fin de pension");
            modelo.addColumn("Importe");
            modelo.addColumn("Recargo");
            modelo.addColumn("IVA");
            modelo.addColumn("Total a pagar");
            modelo.addColumn("Total pagado");
            modelo.addColumn("Fecha de pago");
            modelo.addColumn("Metodo");
            modelo.addColumn("CTE");

//ANCHOS
            int[] anchos = {/*NF*/50, /*NL*/ 50, /*NF*/ 50,/*NE*/ 50, /*AP*/ 60, /*AM*/ 60, /*NAME*/ 50, /*ZON*/ 50,
                /*SERV*/ 50, /*QUIN*/ 60, /*NQ*/ 50, /*PAG*/ 60, /*PEN*/ 60,/*PDODT*/ 60, 70, 70, 70, 70,
                70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70};

            for (int x = 0; x < cantidadColumnas; x++) {
                //Nombre tabla
                Tptetitla.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);

            }

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }
        } catch (SQLException error_mpdodt) {
            JOptionPane.showMessageDialog(null, "Error al motrar pagos de ordenes de taller: " + error_mpdodt.getMessage());

        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Ap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Am = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Direccion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NR = new javax.swing.JTextField();
        TC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TO = new javax.swing.JTextField();
        CEL = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        MAIL = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ObsPen = new javax.swing.JTextArea();
        Placas = new javax.swing.JTextField();
        Marca = new javax.swing.JTextField();
        Modelo = new javax.swing.JTextField();
        año = new javax.swing.JTextField();
        Color = new javax.swing.JTextField();
        CDA = new javax.swing.JTextField();
        TDP = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        RB = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        RS = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        NP = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        IDP = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        FDP = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        Importe = new javax.swing.JTextField();
        Rec = new javax.swing.JCheckBox();
        IVA = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        TAP = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        TP = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        FechaDP = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        Metodo = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        NS = new javax.swing.JTextField();
        RecImporte = new javax.swing.JTextField();
        IVAImporte = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Est = new javax.swing.JComboBox<>();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Titurbide = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        Filiturbide = new javax.swing.JComboBox<>();
        LabelFiliturbide = new javax.swing.JLabel();
        Apiturbide = new javax.swing.JTextField();
        Amiturbide = new javax.swing.JTextField();
        nameiturbide = new javax.swing.JTextField();
        NPiturbide = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        TTehuantepec = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        FilTehuantepec = new javax.swing.JComboBox<>();
        LabelTehuantepec = new javax.swing.JLabel();
        ApTehuantepec = new javax.swing.JTextField();
        AmTehuantepec = new javax.swing.JTextField();
        nameTehuantepec = new javax.swing.JTextField();
        NPTehuantpec = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        Tptetitla = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        Filptetitla = new javax.swing.JComboBox<>();
        LabelFilptetitla = new javax.swing.JLabel();
        Apptetitla = new javax.swing.JTextField();
        Amptetitla = new javax.swing.JTextField();
        nameptetitla = new javax.swing.JTextField();
        NPptetitla = new javax.swing.JTextField();
        AddPen = new javax.swing.JButton();
        Status = new javax.swing.JComboBox<>();
        ModPen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Apellido P:");

        jLabel2.setText("Apellido M:");

        jLabel3.setText("Nombre(s):");

        jLabel4.setText("Direccion:");

        Direccion.setColumns(20);
        Direccion.setRows(5);
        jScrollPane3.setViewportView(Direccion);

        jLabel5.setText("Tel. Casa:");

        jLabel6.setText("# Registro:");

        NR.setEditable(false);
        NR.setText("0");

        jLabel7.setText("Tel Oficina:");

        jLabel8.setText("Celular:");

        jLabel9.setText("Mail:");

        jLabel10.setText("Placas:");

        jLabel11.setText("Marca:");

        jLabel12.setText("Modelo:");

        jLabel13.setText("Año:");

        jLabel14.setText("Color:");

        jLabel15.setText("Clase de Auto:");

        jLabel16.setText("Tipo de pension:");

        jLabel17.setText("Observaciones:");

        ObsPen.setColumns(20);
        ObsPen.setRows(5);
        jScrollPane4.setViewportView(ObsPen);

        jLabel18.setText("Status:");

        jLabel19.setText("Referencia Bancaria:");

        jLabel20.setText("Razon Social:");

        jLabel21.setText("# Padron:");

        NP.setText("0");

        jLabel22.setText("Inicio de pension:");

        jLabel23.setText("Fin de pension:");

        jLabel24.setText("Importe:");

        Importe.setText("0");
        Importe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ImporteKeyReleased(evt);
            }
        });

        Rec.setText("Recargo");
        Rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecActionPerformed(evt);
            }
        });

        IVA.setText("IVA");
        IVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IVAActionPerformed(evt);
            }
        });

        jLabel25.setText("Total a pagar:");

        TAP.setText("0");

        jLabel26.setText("Total Pagado:");

        TP.setText("0");

        jLabel28.setText("Fecha de pago:");

        jLabel29.setText("Metodo:");

        jLabel30.setText("CTE:");

        RecImporte.setEditable(false);
        RecImporte.setText("0");

        IVAImporte.setEditable(false);
        IVAImporte.setText("0");

        jLabel27.setText("Estacionamiento:");

        Est.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "iturbide", "puente titla", "tehuantepec" }));

        Titurbide.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(Titurbide);

        jLabel31.setText("Filtro");

        Filiturbide.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona filtro", "Apellido P", "Apellido M", "Nombre(s)", "# Padron" }));

        LabelFiliturbide.setText("jLabel32");

        Apiturbide.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ApiturbideKeyReleased(evt);
            }
        });

        Amiturbide.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AmiturbideKeyReleased(evt);
            }
        });

        nameiturbide.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameiturbideKeyReleased(evt);
            }
        });

        NPiturbide.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NPiturbideKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1387, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Filiturbide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelFiliturbide)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Apiturbide, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Amiturbide, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameiturbide, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NPiturbide, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(Filiturbide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelFiliturbide)
                    .addComponent(Apiturbide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Amiturbide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameiturbide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NPiturbide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jScrollPane6.setViewportView(jPanel2);

        jTabbedPane2.addTab("Iturbide", jScrollPane6);

        TTehuantepec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(TTehuantepec);

        jLabel32.setText("Filtro");

        FilTehuantepec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona filtro", "Apellido P", "Apellido M", "Nombre(s)", "# Padron" }));

        LabelTehuantepec.setText("jLabel32");

        ApTehuantepec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ApTehuantepecKeyReleased(evt);
            }
        });

        AmTehuantepec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AmTehuantepecKeyReleased(evt);
            }
        });

        nameTehuantepec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTehuantepecKeyReleased(evt);
            }
        });

        NPTehuantpec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NPTehuantpecKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 1387, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FilTehuantepec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelTehuantepec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ApTehuantepec, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AmTehuantepec, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTehuantepec, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NPTehuantpec, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(FilTehuantepec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTehuantepec)
                    .addComponent(ApTehuantepec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AmTehuantepec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTehuantepec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NPTehuantpec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jScrollPane8.setViewportView(jPanel3);

        jTabbedPane2.addTab("Tehuantepec", jScrollPane8);

        Tptetitla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane11.setViewportView(Tptetitla);

        jLabel33.setText("Filtro");

        Filptetitla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona filtro", "Apellido P", "Apellido M", "Nombre(s)", "# Padron" }));

        LabelFilptetitla.setText("jLabel32");

        Apptetitla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ApptetitlaKeyReleased(evt);
            }
        });

        Amptetitla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AmptetitlaKeyReleased(evt);
            }
        });

        nameptetitla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameptetitlaKeyReleased(evt);
            }
        });

        NPptetitla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NPptetitlaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 1387, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Filptetitla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelFilptetitla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Apptetitla, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Amptetitla, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameptetitla, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NPptetitla, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(Filptetitla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelFilptetitla)
                    .addComponent(Apptetitla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Amptetitla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameptetitla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NPptetitla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jScrollPane10.setViewportView(jPanel4);

        jTabbedPane2.addTab("Puente titla", jScrollPane10);

        AddPen.setText("Agregar");
        AddPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPenActionPerformed(evt);
            }
        });

        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".", "Debe", "Pagado" }));

        ModPen.setText("Modificar");
        ModPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModPenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NR, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Placas)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel15))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(Modelo)
                                                    .addComponent(Marca)
                                                    .addComponent(MAIL)
                                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Ap, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Am, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Name, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane4)
                                                .addComponent(TC)
                                                .addComponent(TO)
                                                .addComponent(CEL)
                                                .addComponent(Color)
                                                .addComponent(CDA)
                                                .addComponent(TDP))
                                            .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel26)
                                            .addComponent(Rec)
                                            .addComponent(IVA)))
                                    .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FDP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TAP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(IVAImporte, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(RecImporte, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Importe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(IDP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel27))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(NP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel30))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(RS, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel29))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(RB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel28)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(AddPen)
                                                    .addComponent(TP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ModPen)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(FechaDP, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(Metodo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(NS, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(Est, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 343, Short.MAX_VALUE))
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1417, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Ap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(TC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(RB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(FechaDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Am, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(TO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(RS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(Metodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(CEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(NP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(NS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(IDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel27)
                                    .addComponent(Est, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(FDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(Importe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(MAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)
                                .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Rec)
                            .addComponent(RecImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel15)
                                .addComponent(Placas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(IVA)
                            .addComponent(IVAImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel16)
                            .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(TAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel26)
                            .addComponent(TP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddPen)
                            .addComponent(ModPen)))
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);

        jTabbedPane1.addTab("Registro de pensiones", jScrollPane2);

        jScrollPane1.setViewportView(jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1150, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPenActionPerformed
        String SQL = "INSERT INTO `pensiones." + Est.getSelectedItem().toString() + "` (`#registro`, `Apellido P`, `Apellido M`, `Nombre(s)`, `Direccion`, `Mail`, "
                + "`#Casa`, `#Oficina`, `#Celular`, `Observaciones`, `Placas`, `Marca`, `Modelo`, `Año`, `Color`, `Clase auto`,"
                + " `Tipo de pension`, `Status`, `Referencia Bancaria`, `Razon Social`, `#padron`, `Iniciopension`, `Finpension`, "
                + "`Importe`, `Recargo`, `IVA`, `Total a pagar`, `Total pagado`, `Fecha de pago`, `Metodo`, `CTE`) VALUES "
                + "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try {
            PreparedStatement pst = con.prepareStatement(SQL);
            pst.setInt(1, Integer.parseInt(NR.getText()));
            pst.setString(2, Ap.getText());
            pst.setString(3, Am.getText());
            pst.setString(4, Name.getText());
            pst.setString(5, Direccion.getText());
            pst.setString(6, MAIL.getText());
            pst.setString(7, TC.getText());
            pst.setString(8, TO.getText());
            pst.setString(9, CEL.getText());
            pst.setString(10, ObsPen.getText());
            pst.setString(11, Placas.getText());
            pst.setString(12, Marca.getText());
            pst.setString(13, Modelo.getText());
            pst.setString(14, año.getText());
            pst.setString(15, Color.getText());
            pst.setString(16, CDA.getText());
            pst.setString(17, TDP.getText());
            pst.setString(18, Status.getSelectedItem().toString());
            pst.setString(19, RB.getText());
            pst.setString(20, RS.getText());
            pst.setString(21, NP.getText());
            pst.setString(22, IDP.getText());
            pst.setString(23, FDP.getText());
            pst.setString(24, Importe.getText());
            pst.setString(25, RecImporte.getText());
            pst.setString(26, IVAImporte.getText());
            pst.setString(27, TAP.getText());
            pst.setString(28, TP.getText());
            pst.setString(29, FechaDP.getText());
            pst.setString(30, Metodo.getText());
            pst.setString(31, NS.getText());

            pst.executeUpdate();

            MDPEN();

            NR.setText("0");
            Ap.setText("");
            Am.setText("");
            Name.setText("");
            Direccion.setText("");
            MAIL.setText("");
            TC.setText("");
            TO.setText("");
            CEL.setText("");
            ObsPen.setText("");
            Placas.setText("");
            Marca.setText("");
            Modelo.setText("");
            año.setText("");
            Color.setText("");
            CDA.setText("");
            TDP.setText("");
            Status.setSelectedIndex(0);
            RB.setText("");
            RS.setText("");
            NP.setText("0");
            IDP.setText("");
            FDP.setText("");
            Importe.setText("0");
            RecImporte.setText("0");
            IVAImporte.setText("0");
            TAP.setText("0");
            TP.setText("0");
            FechaDP.setText("");
            Metodo.setText("");
            NS.setText("");

            pst.isClosed();
            JOptionPane.showMessageDialog(null, "pension registrada.");
        } catch (SQLException error_AddLDA) {
            JOptionPane.showMessageDialog(null, "Error al registrar pension: " + error_AddLDA);
        }
    }//GEN-LAST:event_AddPenActionPerformed

    private void ApiturbideKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApiturbideKeyReleased
        MDPEN();
    }//GEN-LAST:event_ApiturbideKeyReleased

    private void AmiturbideKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AmiturbideKeyReleased
        MDPEN();
    }//GEN-LAST:event_AmiturbideKeyReleased

    private void nameiturbideKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameiturbideKeyReleased
        MDPEN();
    }//GEN-LAST:event_nameiturbideKeyReleased

    private void NPiturbideKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NPiturbideKeyReleased
        MDPEN();
    }//GEN-LAST:event_NPiturbideKeyReleased

    private void ImporteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ImporteKeyReleased
        operaciones();
    }//GEN-LAST:event_ImporteKeyReleased

    private void RecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecActionPerformed
        operaciones();
    }//GEN-LAST:event_RecActionPerformed

    private void IVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IVAActionPerformed
        operaciones();
    }//GEN-LAST:event_IVAActionPerformed

    private void ApTehuantepecKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApTehuantepecKeyReleased
        MDPEN();
    }//GEN-LAST:event_ApTehuantepecKeyReleased

    private void AmTehuantepecKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AmTehuantepecKeyReleased
        MDPEN();
    }//GEN-LAST:event_AmTehuantepecKeyReleased

    private void nameTehuantepecKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTehuantepecKeyReleased
        MDPEN();
    }//GEN-LAST:event_nameTehuantepecKeyReleased

    private void NPTehuantpecKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NPTehuantpecKeyReleased
        MDPEN();
    }//GEN-LAST:event_NPTehuantpecKeyReleased

    private void ApptetitlaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApptetitlaKeyReleased
        MDPEN();
    }//GEN-LAST:event_ApptetitlaKeyReleased

    private void AmptetitlaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AmptetitlaKeyReleased
        MDPEN();
    }//GEN-LAST:event_AmptetitlaKeyReleased

    private void nameptetitlaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameptetitlaKeyReleased
        MDPEN();
    }//GEN-LAST:event_nameptetitlaKeyReleased

    private void NPptetitlaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NPptetitlaKeyReleased
        MDPEN();
    }//GEN-LAST:event_NPptetitlaKeyReleased

    private void ModPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModPenActionPerformed
        String SQL = "UPDATE `pensiones." + Est.getSelectedItem().toString() + "` SET `#registro` = ?,"
                + " `Apellido P` = ?, `Apellido M` = ?, `Nombre(s)` = ?, `Direccion` = ?, `Mail` = ?,"
                + " `#Casa` = ?, `#Oficina` = ?, `#Celular` = ?, `Observaciones` = ?, `Placas` = ?,"
                + " `Marca` = ?, `Modelo` = ?, `Año` = ?, `Color` = ?, `Clase auto` = ?, `Tipo de pension` = ?,"
                + " `Status` = ?, `Referencia Bancaria` = ?, `Razon Social` = ?, `#padron` = ?,"
                + " `Iniciopension` = ?, `Finpension` = ?, `Importe` = ?, `Recargo` = ?, `IVA` = ?,"
                + " `Total a pagar` = ?, `Total pagado` = ?, `Fecha de pago` = ?, `Metodo` = ?, `CTE` = ?"
                + " WHERE `pensiones." + Est.getSelectedItem().toString() + "`.`#registro` = ?";
        try {
            PreparedStatement pst = con.prepareStatement(SQL);
            pst.setInt(1, Integer.parseInt(NR.getText()));
            pst.setString(2, Ap.getText());
            pst.setString(3, Am.getText());
            pst.setString(4, Name.getText());
            pst.setString(5, Direccion.getText());
            pst.setString(6, MAIL.getText());
            pst.setString(7, TC.getText());
            pst.setString(8, TO.getText());
            pst.setString(9, CEL.getText());
            pst.setString(10, ObsPen.getText());
            pst.setString(11, Placas.getText());
            pst.setString(12, Marca.getText());
            pst.setString(13, Modelo.getText());
            pst.setString(14, año.getText());
            pst.setString(15, Color.getText());
            pst.setString(16, CDA.getText());
            pst.setString(17, TDP.getText());
            pst.setString(18, Status.getSelectedItem().toString());
            pst.setString(19, RB.getText());
            pst.setString(20, RS.getText());
            pst.setString(21, NP.getText());
            pst.setString(22, IDP.getText());
            pst.setString(23, FDP.getText());
            pst.setString(24, Importe.getText());
            pst.setString(25, RecImporte.getText());
            pst.setString(26, IVAImporte.getText());
            pst.setString(27, TAP.getText());
            pst.setString(28, TP.getText());
            pst.setString(29, FechaDP.getText());
            pst.setString(30, Metodo.getText());
            pst.setString(31, NS.getText());
            pst.setInt(32, Integer.parseInt(NR.getText()));

            pst.executeUpdate();

            MDPEN();

            NR.setText("0");
            Ap.setText("");
            Am.setText("");
            Name.setText("");
            Direccion.setText("");
            MAIL.setText("");
            TC.setText("");
            TO.setText("");
            CEL.setText("");
            ObsPen.setText("");
            Placas.setText("");
            Marca.setText("");
            Modelo.setText("");
            año.setText("");
            Color.setText("");
            CDA.setText("");
            TDP.setText("");
            Status.setSelectedIndex(0);
            RB.setText("");
            RS.setText("");
            NP.setText("0");
            IDP.setText("");
            FDP.setText("");
            Importe.setText("0");
            RecImporte.setText("0");
            IVAImporte.setText("0");
            TAP.setText("0");
            TP.setText("0");
            FechaDP.setText("");
            Metodo.setText("");
            NS.setText("");

            pst.isClosed();
            JOptionPane.showMessageDialog(null, "pension registrada.");
        } catch (SQLException error_AddLDA) {
            JOptionPane.showMessageDialog(null, "Error al registrar pension: " + error_AddLDA);
        }
    }//GEN-LAST:event_ModPenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PensionesVP_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PensionesVP_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PensionesVP_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PensionesVP_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PensionesVP_7().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPen;
    private javax.swing.JTextField Am;
    private javax.swing.JTextField AmTehuantepec;
    private javax.swing.JTextField Amiturbide;
    private javax.swing.JTextField Amptetitla;
    private javax.swing.JTextField Ap;
    private javax.swing.JTextField ApTehuantepec;
    private javax.swing.JTextField Apiturbide;
    private javax.swing.JTextField Apptetitla;
    private javax.swing.JTextField CDA;
    private javax.swing.JTextField CEL;
    private javax.swing.JTextField Color;
    private javax.swing.JTextArea Direccion;
    private javax.swing.JComboBox<String> Est;
    private javax.swing.JTextField FDP;
    private javax.swing.JTextField FechaDP;
    private javax.swing.JComboBox<String> FilTehuantepec;
    private javax.swing.JComboBox<String> Filiturbide;
    private javax.swing.JComboBox<String> Filptetitla;
    private javax.swing.JTextField IDP;
    private javax.swing.JCheckBox IVA;
    private javax.swing.JTextField IVAImporte;
    private javax.swing.JTextField Importe;
    private javax.swing.JLabel LabelFiliturbide;
    private javax.swing.JLabel LabelFilptetitla;
    private javax.swing.JLabel LabelTehuantepec;
    private javax.swing.JTextField MAIL;
    private javax.swing.JTextField Marca;
    private javax.swing.JTextField Metodo;
    private javax.swing.JButton ModPen;
    private javax.swing.JTextField Modelo;
    private javax.swing.JTextField NP;
    private javax.swing.JTextField NPTehuantpec;
    private javax.swing.JTextField NPiturbide;
    private javax.swing.JTextField NPptetitla;
    private javax.swing.JTextField NR;
    private javax.swing.JTextField NS;
    private javax.swing.JTextField Name;
    private javax.swing.JTextArea ObsPen;
    private javax.swing.JTextField Placas;
    private javax.swing.JTextField RB;
    private javax.swing.JTextField RS;
    private javax.swing.JCheckBox Rec;
    private javax.swing.JTextField RecImporte;
    private javax.swing.JComboBox<String> Status;
    private javax.swing.JTextField TAP;
    private javax.swing.JTextField TC;
    private javax.swing.JTextField TDP;
    private javax.swing.JTextField TO;
    private javax.swing.JTextField TP;
    private javax.swing.JTable TTehuantepec;
    private javax.swing.JTable Titurbide;
    private javax.swing.JTable Tptetitla;
    private javax.swing.JTextField año;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField nameTehuantepec;
    private javax.swing.JTextField nameiturbide;
    private javax.swing.JTextField nameptetitla;
    // End of variables declaration//GEN-END:variables
}
