/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author CONFORT
 */
public final class Listas extends javax.swing.JFrame {

    /**
     * Creates new form Listas
     */
    String FG = "";

    public Listas() {
        initComponents();
        //Fecha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Fecha1 = new com.toedter.calendar.JDateChooser();
        Fecha2 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Fecha3 = new com.toedter.calendar.JDateChooser();
        Fecha4 = new com.toedter.calendar.JDateChooser();
        Fecha5 = new com.toedter.calendar.JDateChooser();
        Fecha6 = new com.toedter.calendar.JDateChooser();
        Fecha7 = new com.toedter.calendar.JDateChooser();
        Fecha8 = new com.toedter.calendar.JDateChooser();
        Fecha9 = new com.toedter.calendar.JDateChooser();
        Fecha10 = new com.toedter.calendar.JDateChooser();
        Fecha11 = new com.toedter.calendar.JDateChooser();
        Fecha12 = new com.toedter.calendar.JDateChooser();
        Fecha13 = new com.toedter.calendar.JDateChooser();
        Fecha14 = new com.toedter.calendar.JDateChooser();
        Fecha15 = new com.toedter.calendar.JDateChooser();
        Fecha16 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("LISTA DE ASISTENCIA");

        jLabel1.setText("Quincena:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una Quincena", "1ra Quincena de Enero", "2da Quincena de Enero", "1ra Quincena de Febrero", "2da Quincena de Febrero", "2da Quincena de Feb B", "1ra Quincena de Marzo", "2da Quincena de Marzo", "1ra Quincena de Abril", "2da Quincena de Abril", "1ra Quincena de Mayo", "2da Quincena de Mayo", "1ra Quincena de Junio", "2da Quincena de Junio", "1ra Quincena de Julio", "2da Quincena de Julio", "1ra Quincena de Agosto", "2da Quincena de Agosto", "1ra Quincena de Septiembre", "2da Quincena de Septiembre", "1ra Quincena de Octubre", "2da Quincena de Octubre", "1ra Quincena de Noviembre", "2da Quincena de Noviembre", "1ra Quincena de Diciembre", "2da Quincena de Diciembre" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel3.setText("Fecha:");

        jLabel4.setText("Nombre(s)");

        Fecha1.setDateFormatString("EEEE, d MMM y");

        Fecha2.setDateFormatString("EEEE, d MMM y");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        Fecha3.setDateFormatString("EEEE, d MMM y");

        Fecha4.setDateFormatString("EEEE, d MMM y");

        Fecha5.setDateFormatString("EEEE, d MMM y");

        Fecha6.setDateFormatString("EEEE, d MMM y");

        Fecha7.setDateFormatString("EEEE, d MMM y");

        Fecha8.setDateFormatString("EEEE, d MMM y");

        Fecha9.setDateFormatString("EEEE, d MMM y");

        Fecha10.setDateFormatString("EEEE, d MMM y");

        Fecha11.setDateFormatString("EEEE, d MMM y");

        Fecha12.setDateFormatString("EEEE, d MMM y");

        Fecha13.setDateFormatString("EEEE, d MMM y");

        Fecha14.setDateFormatString("EEEE, d MMM y");

        Fecha15.setDateFormatString("EEEE, d MMM y");

        Fecha16.setDateFormatString("EEEE, d MMM y");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel3)
                                .addGap(102, 102, 102)
                                .addComponent(jLabel4))
                            .addComponent(Fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fecha3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fecha4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fecha5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fecha6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fecha7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fecha8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fecha9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fecha10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fecha11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fecha12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fecha13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fecha14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fecha15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fecha16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(506, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        int vari = jComboBox1.getSelectedIndex();

        // <editor-fold defaultstate="collapsed" desc="Q1 ENE">
        if (vari == 1) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-ene.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);

                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                /*cc.add(Calendar.DATE, 1);
                fin = cc.getTime();*/
                Fecha16.setDate(null);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        //</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 ENE">

        if (vari == 2) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-ene.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);

                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
//</editor-fold>

        // <editor-fold defaultstate="collapsed" desc="Q1 FEB">
        if (vari == 3) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-feb.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);

                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 Feb">

        if (vari == 4) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-feb.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);

                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 Feb B">

        if (vari == 5) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-feb.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);

                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>

        // <editor-fold defaultstate="collapsed" desc="Q1 Marzo">
        if (vari == 6) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 Marzo">

        if (vari == 7) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>

        // <editor-fold defaultstate="collapsed" desc="Q1 Abril">
        if (vari == 8) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-abr.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 abril">

        if (vari == 9) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-abr.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        
        // <editor-fold defaultstate="collapsed" desc="Q1 may">
        if (vari == 10) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-may.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 Marzo">

        if (vari == 6) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q1 Marzo">
        if (vari == 6) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 Marzo">

        if (vari == 6) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q1 Marzo">
        if (vari == 6) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 Marzo">

        if (vari == 6) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q1 Marzo">
        if (vari == 6) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 Marzo">

        if (vari == 6) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q1 Marzo">
        if (vari == 6) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 Marzo">

        if (vari == 6) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q1 Marzo">
        if (vari == 6) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 Marzo">

        if (vari == 6) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q1 Marzo">
        if (vari == 6) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 Marzo">

        if (vari == 6) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q1 Marzo">
        if (vari == 6) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 Marzo">

        if (vari == 6) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    public void Fecha() {
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Listas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fecha1;
    private com.toedter.calendar.JDateChooser Fecha10;
    private com.toedter.calendar.JDateChooser Fecha11;
    private com.toedter.calendar.JDateChooser Fecha12;
    private com.toedter.calendar.JDateChooser Fecha13;
    private com.toedter.calendar.JDateChooser Fecha14;
    private com.toedter.calendar.JDateChooser Fecha15;
    private com.toedter.calendar.JDateChooser Fecha16;
    private com.toedter.calendar.JDateChooser Fecha2;
    private com.toedter.calendar.JDateChooser Fecha3;
    private com.toedter.calendar.JDateChooser Fecha4;
    private com.toedter.calendar.JDateChooser Fecha5;
    private com.toedter.calendar.JDateChooser Fecha6;
    private com.toedter.calendar.JDateChooser Fecha7;
    private com.toedter.calendar.JDateChooser Fecha8;
    private com.toedter.calendar.JDateChooser Fecha9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
