/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Conexion.ConexionSQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JDeat
 */
public final class Listas extends javax.swing.JFrame {

    /**
     * Creates new form Listas
     */
    String FG = "";
    ConexionSQL cc = new ConexionSQL();
    Connection con = cc.conexion();

    public Listas() {
        initComponents();

        // <editor-fold defaultstate="collapsed" desc="Campos invisibles">
        Fecha2.setVisible(false);
        Fecha3.setVisible(false);
        Fecha4.setVisible(false);
        Fecha5.setVisible(false);
        Fecha6.setVisible(false);
        Fecha7.setVisible(false);
        Fecha8.setVisible(false);
        Fecha9.setVisible(false);
        Fecha10.setVisible(false);
        Fecha11.setVisible(false);
        Fecha12.setVisible(false);
        Fecha13.setVisible(false);
        Fecha14.setVisible(false);
        Fecha15.setVisible(false);
        Fecha16.setVisible(false);
// </editor-fold>

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LDAQuin = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Fecha1 = new com.toedter.calendar.JDateChooser();
        Fecha2 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Fecha3 = new com.toedter.calendar.JDateChooser();
        Fecha4 = new com.toedter.calendar.JDateChooser();
        Fecha5 = new com.toedter.calendar.JDateChooser();
        Fecha6 = new com.toedter.calendar.JDateChooser();
        Fecha7 = new com.toedter.calendar.JDateChooser();
        Fecha8 = new com.toedter.calendar.JDateChooser();
        Fecha9 = new com.toedter.calendar.JDateChooser();
        Fecha10 = new com.toedter.calendar.JDateChooser();
        Fecha11 = new com.toedter.calendar.JDateChooser();
        Fecha12 = new com.toedter.calendar.JDateChooser();
        Fecha13 = new com.toedter.calendar.JDateChooser();
        Fecha14 = new com.toedter.calendar.JDateChooser();
        Fecha15 = new com.toedter.calendar.JDateChooser();
        Fecha16 = new com.toedter.calendar.JDateChooser();
        LDAAp = new javax.swing.JTextField();
        LDAAm = new javax.swing.JTextField();
        LDAName = new javax.swing.JTextField();
        NLDA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CI = new javax.swing.JCheckBox();
        MTL = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        EmpleadosSh = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        LDAfil = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        LDAfilname = new javax.swing.JTextField();
        LDAfilap = new javax.swing.JTextField();
        LDAfilam = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("LISTA DE ASISTENCIA");

        jLabel1.setText("Quincena:");

        LDAQuin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una Quincena", "1ra Quincena de Enero", "2da Quincena de Enero", "1ra Quincena de Febrero", "2da Quincena de Febrero", "2da Quincena de Feb B", "1ra Quincena de Marzo", "2da Quincena de Marzo", "1ra Quincena de Abril", "2da Quincena de Abril", "1ra Quincena de Mayo", "2da Quincena de Mayo", "1ra Quincena de Junio", "2da Quincena de Junio", "1ra Quincena de Julio", "2da Quincena de Julio", "1ra Quincena de Agosto", "2da Quincena de Agosto", "1ra Quincena de Septiembre", "2da Quincena de Septiembre", "1ra Quincena de Octubre", "2da Quincena de Octubre", "1ra Quincena de Noviembre", "2da Quincena de Noviembre", "1ra Quincena de Diciembre", "2da Quincena de Diciembre" }));
        LDAQuin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                LDAQuinItemStateChanged(evt);
            }
        });

        jLabel3.setText("Fecha:");

        jLabel4.setText("Nombre(s)");

        Fecha1.setDateFormatString("EEEE, d MMM y");

        Fecha2.setDateFormatString("EEEE, d MMM y");

        jLabel5.setText("Apellido P");

        jLabel6.setText("Apellido M:");

        Fecha3.setDateFormatString("EEEE, d MMM y");

        Fecha4.setDateFormatString("EEEE, d MMM y");

        Fecha5.setDateFormatString("EEEE, d MMM y");

        Fecha6.setDateFormatString("EEEE, d MMM y");

        Fecha7.setDateFormatString("EEEE, d MMM y");

        Fecha8.setDateFormatString("EEEE, d MMM y");

        Fecha9.setDateFormatString("EEEE, d MMM y");

        Fecha10.setDateFormatString("EEEE, d MMM y");

        Fecha11.setDateFormatString("EEEE, d MMM y");

        Fecha12.setDateFormatString("EEEE, d MMM y");

        Fecha13.setDateFormatString("EEEE, d MMM y");

        Fecha14.setDateFormatString("EEEE, d MMM y");

        Fecha15.setDateFormatString("EEEE, d MMM y");

        Fecha16.setDateFormatString("EEEE, d MMM y");

        jLabel8.setText("# Lista");

        CI.setText("Con imss");

        MTL.setText("Mostrar todas las Fechas.");
        MTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MTLActionPerformed(evt);
            }
        });

        EmpleadosSh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(EmpleadosSh);

        jLabel9.setText("Filtrar por:");

        LDAfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona filtro", "Apellido P", "Apellido M", "Nombre(s)" }));

        jLabel10.setText("jLabel10");

        LDAfilname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LDAfilnameKeyReleased(evt);
            }
        });

        LDAfilap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LDAfilapKeyReleased(evt);
            }
        });

        LDAfilam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LDAfilamKeyReleased(evt);
            }
        });

        jLabel7.setText("Zona");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha15, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha16, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(LDAAp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LDAAm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(LDAName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MTL)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LDAQuin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NLDA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CI))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LDAfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LDAfilname, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LDAfilap, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LDAfilam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(LDAfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(LDAfilname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LDAfilap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LDAfilam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NLDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(CI)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MTL)
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(LDAQuin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LDAAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LDAAm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LDAName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void SHempleados() {
        //Buscar empleado
        String Share = LDAfilname.getText();
        String ShareAP = LDAfilap.getText();
        String ShareAM = LDAfilam.getText();
        String SQL = "select `Apellido P`, `Apellido M`, `Nombre(s)`, `Zona` "
                + " from empleados  where `Status` LIKE '%Vigente%'";

        if (!"".equals(Share)) {
            SQL = " select `Apellido P`, `Apellido M`, `Nombre(s)`, `Zona` "
                    + "from empleados WHERE `Nombre(s)` LIKE '%" + Share + "%'";
        } else if (!"".equals(ShareAP)) {
            SQL = " select `Apellido P`, `Apellido M`, `Nombre(s)`, `Zona` "
                    + "from empleados WHERE `Apellido P` LIKE '%" + ShareAP + "%'";
        } else if (!"".equals(ShareAM)) {
            SQL = " select `Apellido P`, `Apellido M`, `Nombre(s)`, `Zona` "
                    + "from empleados WHERE `Apellido M` LIKE '%" + ShareAM + "%'";
        }

        try {
            //Cargar datos
            DefaultTableModel modelo = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int filas, int columna) {
                    return false;
                }

            };
//Nombre de la tabla
            EmpleadosSh.setModel(modelo);
            PreparedStatement ps;
            ResultSet rs;

            ps = con.prepareStatement(SQL);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Apellido P");//1
            modelo.addColumn("Apellido M");
            modelo.addColumn("Nombre(s)");//3
            modelo.addColumn("Servicio");
            modelo.addColumn("Zona");

//Anchos
            int[] anchos = {50, 50, 100, 75, 50};

            for (int x = 0; x < cantidadColumnas; x++) {
                //Nombre tabla
                EmpleadosSh.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);

            }

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al compartir datos con prestamos: " + ex.getMessage());

        }

    }


    private void LDAQuinItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_LDAQuinItemStateChanged
        int vari = LDAQuin.getSelectedIndex();

        // <editor-fold defaultstate="collapsed" desc="Q1 ENE">
        if (vari == 1) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-ene.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);

                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                /*cc.add(Calendar.DATE, 1);
                fin = cc.getTime();*/
                Fecha16.setDate(null);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        //</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 ENE">

        if (vari == 2) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-ene.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);

                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
//</editor-fold>

        // <editor-fold defaultstate="collapsed" desc="Q1 FEB">
        if (vari == 3) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-feb.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);

                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 Feb">

        if (vari == 4) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-feb.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);

                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 Feb B">

        if (vari == 5) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-feb.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);

                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>

        // <editor-fold defaultstate="collapsed" desc="Q1 Marzo">
        if (vari == 6) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 Marzo">

        if (vari == 7) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-mar.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>

        // <editor-fold defaultstate="collapsed" desc="Q1 Abril">
        if (vari == 8) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-abr.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 abril">

        if (vari == 9) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-abr.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>

        // <editor-fold defaultstate="collapsed" desc="Q1 may">
        if (vari == 10) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-may.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 may">

        if (vari == 11) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-may.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>

        // <editor-fold defaultstate="collapsed" desc="Q1 junio">
        if (vari == 12) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-jun.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 jun">

        if (vari == 13) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-jun.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>

        // <editor-fold defaultstate="collapsed" desc="Q1 jul">
        if (vari == 14) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-jul.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 jul">

        if (vari == 15) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-jul.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>

        // <editor-fold defaultstate="collapsed" desc="Q1 ago">
        if (vari == 16) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-ago.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 ago">

        if (vari == 17) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-ago.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>

        // <editor-fold defaultstate="collapsed" desc="Q1 sep">
        if (vari == 18) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-sep.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 sep">

        if (vari == 19) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-sep.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>

        // <editor-fold defaultstate="collapsed" desc="Q1 oct">
        if (vari == 20) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-oct.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 oct">

        if (vari == 21) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-oct.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>

        // <editor-fold defaultstate="collapsed" desc="Q1 nov">
        if (vari == 22) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-nov.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 nov">

        if (vari == 23) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-nov.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>

        // <editor-fold defaultstate="collapsed" desc="Q1 dic">
        if (vari == 24) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 1-dic.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Q2 dic">

        if (vari == 25) {
            try {
                Date DTano = new Date();
                SimpleDateFormat ano = new SimpleDateFormat("y");
                SimpleDateFormat dias = new SimpleDateFormat("EEEE");
                FG = dias.format(DTano) + ", 16-dic.-" + ano.format(DTano);
                Date fin = new SimpleDateFormat("EEEE, d-MMM-y").parse(FG);
                Fecha1.setDate(fin);
                Calendar cc = Calendar.getInstance();
                cc.setTime(fin);

                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha2.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha3.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha4.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha5.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha6.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha7.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha8.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha9.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha10.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha11.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha12.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha13.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha14.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha15.setDate(fin);
                cc.add(Calendar.DATE, 1);
                fin = cc.getTime();
                Fecha16.setDate(fin);
            } catch (ParseException ex) {
                Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//</editor-fold>

    }//GEN-LAST:event_LDAQuinItemStateChanged

    private void MTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MTLActionPerformed
        if (MTL.isSelected() == false) {
            Fecha2.setVisible(false);
            Fecha3.setVisible(false);
            Fecha4.setVisible(false);
            Fecha5.setVisible(false);
            Fecha6.setVisible(false);
            Fecha7.setVisible(false);
            Fecha8.setVisible(false);
            Fecha9.setVisible(false);
            Fecha10.setVisible(false);
            Fecha11.setVisible(false);
            Fecha12.setVisible(false);
            Fecha13.setVisible(false);
            Fecha14.setVisible(false);
            Fecha15.setVisible(false);
            Fecha16.setVisible(false);
        }
        if (MTL.isSelected() == true) {
            Fecha2.setVisible(true);
            Fecha3.setVisible(true);
            Fecha4.setVisible(true);
            Fecha5.setVisible(true);
            Fecha6.setVisible(true);
            Fecha7.setVisible(true);
            Fecha8.setVisible(true);
            Fecha9.setVisible(true);
            Fecha10.setVisible(true);
            Fecha11.setVisible(true);
            Fecha12.setVisible(true);
            Fecha13.setVisible(true);
            Fecha14.setVisible(true);
            Fecha15.setVisible(true);
            Fecha16.setVisible(true);
        }
    }//GEN-LAST:event_MTLActionPerformed

    private void LDAfilapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LDAfilapKeyReleased
        SHempleados();
    }//GEN-LAST:event_LDAfilapKeyReleased

    private void LDAfilnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LDAfilnameKeyReleased
        SHempleados();
    }//GEN-LAST:event_LDAfilnameKeyReleased

    private void LDAfilamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LDAfilamKeyReleased
        SHempleados();
    }//GEN-LAST:event_LDAfilamKeyReleased

    public void Fecha() {
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Listas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CI;
    private javax.swing.JTable EmpleadosSh;
    private com.toedter.calendar.JDateChooser Fecha1;
    private com.toedter.calendar.JDateChooser Fecha10;
    private com.toedter.calendar.JDateChooser Fecha11;
    private com.toedter.calendar.JDateChooser Fecha12;
    private com.toedter.calendar.JDateChooser Fecha13;
    private com.toedter.calendar.JDateChooser Fecha14;
    private com.toedter.calendar.JDateChooser Fecha15;
    private com.toedter.calendar.JDateChooser Fecha16;
    private com.toedter.calendar.JDateChooser Fecha2;
    private com.toedter.calendar.JDateChooser Fecha3;
    private com.toedter.calendar.JDateChooser Fecha4;
    private com.toedter.calendar.JDateChooser Fecha5;
    private com.toedter.calendar.JDateChooser Fecha6;
    private com.toedter.calendar.JDateChooser Fecha7;
    private com.toedter.calendar.JDateChooser Fecha8;
    private com.toedter.calendar.JDateChooser Fecha9;
    private javax.swing.JTextField LDAAm;
    private javax.swing.JTextField LDAAp;
    private javax.swing.JTextField LDAName;
    private javax.swing.JComboBox<String> LDAQuin;
    private javax.swing.JComboBox<String> LDAfil;
    private javax.swing.JTextField LDAfilam;
    private javax.swing.JTextField LDAfilap;
    private javax.swing.JTextField LDAfilname;
    private javax.swing.JCheckBox MTL;
    private javax.swing.JTextField NLDA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
